services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /opt/app/data/mongo:/data/db

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/testProjekt
    depends_on:
      - mongo
    ports: ["8080:8080"]

  frontend:
    build:
      context: ../frontend       # <— dein Ordner heißt "frontend"
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports: ["5500:80"]